apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-1-0
  namespace: ratingsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      version: "1.0"
  template:
    metadata:
      labels:
        app: voting-app
        version: "1.0"
    spec:
      containers:
      - name: voting-app
        image: mcr.microsoft.com/aks/samples/voting/app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SHOWDETAILS
          value: "true"
        - name: FEATUREFLAG
          value: "true"
        - name: REDIS_HOST
          value: "voting-storage"
        - name: ANALYTICS_HOST
          value: "voting-analytics"
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app
  namespace: ratingsapp
  labels: 
    app: voting-app
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: voting-app