# Default values
# https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
image:
  repository: bitnamilegacy/redis

usePassword: false
cluster:
  enabled: false
master:
  persistence:
    enabled: false
replica:
  persistence:
    enabled: false

volumePermissions:
  enabled: true
