# Default values
# https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
usePassword: false
cluster:
  enabled: false
master:
  persistence:
    enabled: false
replica:
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  containerSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

volumePermissions:
  enabled: true
  runAsUser: 1001

sentinel:
  enabled: true
  debug: true
