apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: cluster-config
spec:
  chart:
    spec:
      version: "6.3.2"
  test:
    enable: false
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
      hosts:
        - host: podinfo.appgw
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  number: 80          
