apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: cluster-config
spec:
  chart:
    spec:
      version: "6.3.5"
  test:
    enable: false
  values:
    # ingress:
    #   annotations:
        # kubernetes.io/ingress.class: addon-http-application-routing
    # cache: redis-master.redis:6379
    # color: blue
    # ui:
    #   color: blue
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: podinfo.appgw
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  number: 80          
