apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: cluster-config
spec:
  chart:
    spec:
<<<<<<< HEAD
      version: "6.3.3"
=======
      version: "6.3.2"
>>>>>>> 84378032d2c5b21bbbff79541955710cfed5ba9d
  values:
    ingress:
      hosts:
        - host: podinfo.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
